package tool.xfy9326.naucourse.constants

object PrefConst {
    const val CourseCellTextSize = "CourseCellTextSize"
    const val ClearNetworkCache = "ClearNetworkCache"
    const val ApplicationUpdate = "ApplicationUpdate"
    const val ClearDebugLogs = "ClearDebugLogs"
    const val AboutIntent = "AboutIntent"
    const val NightMode = "NightMode"
    const val DebugMode = "DebugMode"
    const val NotifyNextCourse = "NotifyNextCourse"
    const val ForceShowCourseTableWeekends = "ForceShowCourseTableWeekends"
    const val SameCourseCellHeight = "SameCourseCellHeight"
    const val CenterHorizontalShowCourseText = "CenterHorizontalShowCourseText"
    const val CenterVerticalShowCourseText = "CenterVerticalShowCourseText"
    const val DrawAllCellBackground = "DrawAllCellBackground"
    const val UseRoundCornerCourseCell = "UseRoundCornerCourseCell"
    const val CourseTableRoundCompat = "CourseTableRoundCompat"
    const val CheckUpdatesNow = "CheckUpdatesNow"
    const val CustomCourseTableBackground = "CustomCourseTableBackground"
    const val ChooseCourseTableBackgroundPicture = "ChooseCourseTableBackgroundPicture"
    const val CustomCourseTableAlpha = "CustomCourseTableAlpha"
    const val CourseTableImageQuality = "CourseTableImageQuality"
    const val CourseTableBackgroundScareType = "CourseTableBackgroundScareType"
    const val CourseTableBackgroundAlpha = "CourseTableBackgroundAlpha"
    const val ShowNextWeekCourseTableAhead = "ShowNextWeekCourseTableAhead"
    const val CourseTableBackgroundFullScreen = "CourseTableBackgroundFullScreen"
    const val ShowNotThisWeekCourseInTable = "ShowNotThisWeekCourseInTable"
    const val CourseTableTimeTextColor = "CourseTableTimeTextColor"
    const val EnableCourseTableTimeTextColor = "EnableCourseTableTimeTextColor"
    const val HighLightCourseTableTodayDate = "HighLightCourseTableTodayDate"
    const val NotThisWeekCourseShowType = "NotThisWeekCourseShowType"
    const val DefaultEnterInterface = "DefaultEnterInterface"
}