package tool.xfy9326.naucourse.tools

enum class NotifyType {
    NIGHT_MODE_CHANGED,
    COURSE_TERM_UPDATE,
    COURSE_ASYNC_UPDATE,
    COURSE_INIT_CONFLICT,
    COURSE_STYLE_TERM_UPDATE,
    REBUILD_COURSE_TABLE,
    REBUILD_COURSE_TABLE_BACKGROUND,
    ADVANCED_FUNCTION_MODE_CHANGED,
    DEFAULT_ENTER_INTERFACE_CHANGED
}